version: '3'
services:
    job_search:
        tty: true
        build:
            context: .
            args:
                - CONFIG_PATH=configs/cloud.cfg
        restart: always
        ports:
            - "5000:5000"
        volumes:
            - .:/code
